/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import config.PassWordH;
import config.dbConnector;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class CreateUsersF extends javax.swing.JFrame {

    /**
     * Creates new form registF
     */
    public CreateUsersF() {
        initComponents();
    }
    
    public static String email,username;
            
    
    public boolean duplicateCheck(){
        
       dbConnector dbc = new dbConnector();
        
        try{
            String query = "SELECT * FROM users  WHERE u_username = '" + Un.getText() + "' OR u_email = '" + mail.getText() + "'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                email = resultSet.getString("u_email");
                if(email.equals(mail.getText())){
                      JOptionPane.showMessageDialog(null, "Email is Already Used!");
                      mail.setText("");
                }
                username = resultSet.getString("u_username");
                if(username.equals(Un.getText())){
                      JOptionPane.showMessageDialog(null, "Email is Already Used!");
                      Un.setText("");
            }
            return true;
            }else{
                return false;
            }
          
        }catch (SQLException ex) {
            System.out.println(""+ex);
            return false;
        }
    }
    
    public boolean UpdateCheck(){
        
       dbConnector dbc = new dbConnector();
        
        try{
            String query = "SELECT * FROM users WHERE (u_username = '" +Un.getText()+ "' OR u_email = '" +mail.getText()+ "') AND u_id != '"+id.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){ 
                email = resultSet.getString("u_email");
   
                if(email.equals(mail.getText())){
                    JOptionPane.showMessageDialog(null, "Email is already used!");
                    mail.setText("");
                    
                }
                    
                username = resultSet.getString("u_username");
                if(username.equals(Un.getText())){
                    JOptionPane.showMessageDialog(null, "Username is already used!");
                    Un.setText("");
                    
                }
                return true;
            }else{
                return false;
                
            }
            
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ln = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        cc = new javax.swing.JButton();
        Un = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        PassWord = new javax.swing.JLabel();
        rf = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        stat = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        up = new javax.swing.JButton();
        cl = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        ln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnMouseClicked(evt);
            }
        });
        jPanel4.add(ln);
        ln.setBounds(220, 0, 190, 30);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 420, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email");
        jPanel5.add(Email);
        Email.setBounds(140, 0, 31, 30);
        jPanel5.add(mail);
        mail.setBounds(220, 0, 190, 30);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 420, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        UserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName.setText("UserName");
        jPanel6.add(UserName);
        UserName.setBounds(140, 0, 59, 30);

        cc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cc.setForeground(new java.awt.Color(153, 0, 153));
        cc.setText("CANCEL");
        cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccMouseClicked(evt);
            }
        });
        jPanel6.add(cc);
        cc.setBounds(10, 0, 90, 30);
        jPanel6.add(Un);
        Un.setBounds(220, 0, 190, 30);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 420, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        PassWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PassWord.setText("PassWord");
        jPanel7.add(PassWord);
        PassWord.setBounds(140, 0, 70, 30);

        rf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rf.setForeground(new java.awt.Color(102, 0, 255));
        rf.setText("REFRESH");
        rf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rfMouseClicked(evt);
            }
        });
        jPanel7.add(rf);
        rf.setBounds(10, 0, 90, 30);

        pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwMouseClicked(evt);
            }
        });
        jPanel7.add(pw);
        pw.setBounds(220, 0, 190, 30);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 420, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER DIAGNOSIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 330, 60));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("User Status");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 0, 90, 30);

        ut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin", " " }));
        jPanel8.add(ut);
        ut.setBounds(90, 0, 190, 30);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 290, 30));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.setLayout(null);

        stat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        jPanel9.add(stat);
        stat.setBounds(90, 0, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User Type");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(0, 0, 90, 30);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 290, 30));

        check.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check.setText("show");
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, 20));

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 0, 0));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        del.setForeground(new java.awt.Color(255, 51, 51));
        del.setText("DELETE");
        del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delMouseClicked(evt);
            }
        });
        jPanel1.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 30));

        up.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        up.setForeground(new java.awt.Color(0, 0, 255));
        up.setText("UPDATE");
        up.setEnabled(false);
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upMouseClicked(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 30));

        cl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cl.setForeground(new java.awt.Color(0, 0, 255));
        cl.setText("CLEAR");
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
        });
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("First Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 30));

        fn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnMouseClicked(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rfMouseClicked

    private void ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccMouseClicked
    userLoginF usf = new userLoginF();
        usf.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ccMouseClicked

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clMouseClicked

    private void upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseClicked
 if(fn.getText().isEmpty()|| ln.getText().isEmpty() || mail.getText().isEmpty()
            || Un.getText().isEmpty()|| pw.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pw.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Characters password is 8 above!");
            pw.setText("");
        }else if(UpdateCheck()){
            System.out.println("Duplicate Exist!");

        }else{
            dbConnector dbc = new dbConnector();
            dbc.updateData("UPDATE users SET u_fname ='"+fn.getText()+"', u_lname ='"+ln.getText()+"', u_email ='"+mail.getText()+"', u_username ='"+Un.getText()+"'");

            JOptionPane.showMessageDialog(null, "UPDATED SUCCESSFULLY!");
            userLoginF ads = new userLoginF();
            ads.setVisible(true);
            this.dispose();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_upMouseClicked

    private void pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pwMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

        if(fn.getText().isEmpty()|| ln.getText().isEmpty() || mail.getText().isEmpty()
            || Un.getText().isEmpty()|| pw.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(pw.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Characters password is 8 above!");
            pw.setText("");
        }else if(duplicateCheck()){
            System.out.println("Duplicate Exist!");

        }else{

            dbConnector dbc = new dbConnector();
            try{
                String pass = PassWordH.hashPassword(pw.getText());

                if (dbc.insertData("INSERT INTO users (u_fname, u_lname, u_email, u_username, u_password, u_type, u_status)VALUES('"
                    + fn.getText() + "','"+ln.getText()+"','"+ mail.getText() + "','"
                    + Un.getText() + "','" + pass + "','"+ ut.getSelectedItem() + "','"+stat.getSelectedItem()+"')")){

                JOptionPane.showMessageDialog(null, "Inserted Successfully!");
                userLoginF ads = new userLoginF();
                ads.setVisible(true);
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(null, "Connection Error!");
            }
        }catch(NoSuchAlgorithmException ex) {
            System.out.println(""+ex);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delMouseClicked

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
  boolean isSelected = check.isSelected();

        if (isSelected) {
            pw.setEchoChar((char)0);
        } else {
            pw.setEchoChar('*');
        }        // TODO add your handling code here:
    }//GEN-LAST:event_checkMouseClicked

    private void fnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fnMouseClicked

    private void lnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lnMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUsersF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel PassWord;
    private javax.swing.JTextField Un;
    private javax.swing.JLabel UserName;
    public javax.swing.JButton add;
    private javax.swing.JButton cc;
    private javax.swing.JCheckBox check;
    private javax.swing.JButton cl;
    private javax.swing.JButton del;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mail;
    public javax.swing.JPasswordField pw;
    private javax.swing.JButton rf;
    public javax.swing.JComboBox<String> stat;
    public javax.swing.JButton up;
    public javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
